{% set name = "openshift-cli" %}
{% set version = "4.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # Tarballs are not used as the build system relies heavily on the state of
  # the git repository and updates will be difficult if it's patched with
  # these details
  git_url: https://github.com/openshift/origin.git
  git_rev: v{{ version }}

build:
  number: 2
  skip: true  # [win]
  script:
    - make build WHAT=cmd/oc
    # For go 1.16 add @v$PKG_VERSION
    - cp _output/local/bin/*/*/oc $PREFIX/bin

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    # GO 1.16 has issues but there haven't been any releases in a while so it's not worth fixing
    - {{ compiler("cgo") }} 1.15.*
    - make
  host:
    - krb5
    - socat  # [unix]
  run:
    - krb5
    - socat  # [unix]

test:
  commands:
      - oc --help

about:
  home: https://www.okd.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'OpenShift Client'

  description: |
    This client helps you develop, build, deploy, and run your applications on any
    OpenShift or Kubernetes cluster. It also includes the administrative
    commands for managing a cluster under the 'adm' subcommand.
  dev_url: https://github.com/openshift/origin
  doc_url: https://docs.okd.io/latest/cli_reference/index.html

extra:
  recipe-maintainers:
    - chrisburr
