{% set name = "openshift-cli" %}
{% set version = "4.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/openshift/oc.git
  git_rev: openshift-clients-{{ version }}-202406131906

build:
  number: 0
  skip: true  # [win]
  script:
    - make oc
    - cp oc $PREFIX/bin/  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('go-cgo') }}
    - make
    - git
  host:
    - krb5
  run:
    - krb5

test:
  commands:
    - oc --help

about:
  homepage: https://www.okd.io/
  summary: OpenShift Command Line Interface
  description: |
    The OpenShift Command Line Interface (CLI), is a set of tools built on top of kubectl
    that help you work with OpenShift. With the CLI, you can create applications and manage
    OpenShift resources. It provides its full capabilities to connect with any Kubernetes
    compliant cluster, and adds commands simplifying interaction with an OpenShift cluster.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/openshift/oc
  doc_url: https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html

extra:
  recipe-maintainers:
    - chrisburr
    - delsner
