schema_version: 1

context:
  name: "openshift-client"
  version: "4.19.15"

package:
  name: "openshift-cli"
  version: ${{ version }}

source:
  url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${{ version }}/${{ name }}-src.tar.gz
  sha256: 4c23bda233eaac582b812b9d4783be71f218de5124d673b4325377e8f325be2c

build:
  number: 0
  script:
    - if: unix
      then:
        - export GO111MODULE=on
        - go build -mod=vendor -tags 'include_gcs include_oss containers_image_openpgp' -ldflags "-X github.com/openshift/oc/pkg/version.versionFromGit=v$PKG_VERSION -X github.com/openshift/oc/pkg/version.gitTreeState=clean" -o oc ./cmd/oc
        - go-licenses csv ./cmd/oc > licenses.csv || touch licenses.csv
        - go-licenses save ./cmd/oc --save_path=licenses/ || mkdir -p licenses
        - mkdir -p $PREFIX/bin/
        - mkdir -p $PREFIX/share/doc/$PKG_NAME/
        - cp oc $PREFIX/bin/
        - cp oc $PREFIX/bin/okd-cli
    - if: win
      then:
        - set GO111MODULE=on
        - go build -mod=vendor -tags "include_gcs include_oss containers_image_openpgp" -ldflags "-X github.com/openshift/oc/pkg/version.versionFromGit=v%PKG_VERSION% -X github.com/openshift/oc/pkg/version.gitTreeState=clean" -o oc.exe ./cmd/oc
        - go-licenses csv ./cmd/oc > licenses.csv || echo. > licenses.csv
        - go-licenses save ./cmd/oc --save_path=licenses/ || mkdir licenses
        - if not exist "%PREFIX%\bin" mkdir "%PREFIX%\bin"
        - if not exist "%PREFIX%\share\doc\%PKG_NAME%" mkdir "%PREFIX%\share\doc\%PKG_NAME%"
        - copy oc.exe "%PREFIX%\bin\oc.exe"
        - copy oc.exe "%PREFIX%\bin\okd-cli.exe"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then:
        - ${{ stdlib('c') }}
    - ${{ compiler('go-nocgo') }} >=1.15.2
    - go-licenses >=2.0.1
    - if: unix
      then:
        - make >=4.0
    - git >=2.0
    - krb5 >=1.21
    - pkg-config >=0.29

tests:
  - package_contents:
      bin:
        - oc
        - okd-cli
  - script:
      - oc --help

about:
  homepage: https://www.okd.io/
  summary: OpenShift Command Line Interface
  description: |
    The OpenShift Command Line Interface (CLI), is a set of tools built on top of kubectl
    that help you work with OpenShift. With the CLI, you can create applications and manage
    OpenShift resources. It provides its full capabilities to connect with any Kubernetes
    compliant cluster, and adds commands simplifying interaction with an OpenShift cluster.
  license: Apache-2.0
  license_file:
    - LICENSE
    - licenses.csv
    - licenses/
  repository: https://github.com/openshift/oc
  documentation: https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html

extra:
  recipe-maintainers:
    - chrisburr
    - delsner
    - phreed
