schema_version: 1

# Context section replaces set variables
context:
  name: "openshift-cli"
  version: "4.16.0"

# Package information
package:
  name: ${{ name|lower }}
  version: ${{ version }}

# Source section
source:
  git: https://github.com/openshift/oc.git
  # Using commit SHA instead of tag due to rattler-build checkout issues
  rev: a2450418f7b12a71e8f3562a4e9aa8a976bbf85b # openshift-clients-4.16.0-202406131906

# Build configuration
build:
  number: 0
  script:
    # Disable GSSAPI to avoid missing Go bindings
    - make oc GO_BUILD_FLAGS="-mod=vendor -tags 'include_gcs include_oss containers_image_openpgp'"
    - if: unix
      then:
        - cp oc $PREFIX/bin/
    - if: win
      then:
        - cp oc.exe $PREFIX/bin/oc.exe

# Requirements
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    # - ${{ stdlib('c') }}
    - go >=1.15.2
    - make
    - git
    - krb5-static
    - pkg-config
  host:
    - krb5
  run:
    - krb5

# Tests
tests:
  - script:
      - oc --help

# About section
about:
  homepage: https://www.okd.io/
  summary: OpenShift Command Line Interface
  description: |
    The OpenShift Command Line Interface (CLI), is a set of tools built on top of kubectl
    that help you work with OpenShift. With the CLI, you can create applications and manage
    OpenShift resources. It provides its full capabilities to connect with any Kubernetes
    compliant cluster, and adds commands simplifying interaction with an OpenShift cluster.
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/openshift/oc
  documentation: https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html

# Extra section
extra:
  recipe-maintainers:
    - chrisburr
    - delsner
