schema_version: 1

context:
  name: "openshift-client"
  version: "4.19.15"

package:
  name: "openshift-cli"
  version: ${{ version }}

source:
  url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${{ version }}/${{ name }}-src.tar.gz
  sha256: 4c23bda233eaac582b812b9d4783be71f218de5124d673b4325377e8f325be2c

build:
  number: 0
  script:
    - go-licenses save ./cmd/oc --save_path ./library_licenses/
    - if: unix
      then:
        - export TAGS='include_gcs include_oss containers_image_openpgp'
        - export LDFLAGS="-X github.com/openshift/oc/pkg/version.versionFromGit=v$PKG_VERSION -X github.com/openshift/oc/pkg/version.gitTreeState=clean"
        - go build -o $PREFIX/bin/oc -mod=vendor -tags "$TAGS" -ldflags "$LDFLAGS" ./cmd/oc
        - cp $PREFIX/bin/oc $PREFIX/bin/okd-cli
    - if: win
      then:
        - set TAGS=include_gcs include_oss containers_image_openpgp
        - set LDFLAGS=-X github.com/openshift/oc/pkg/version.versionFromGit=v%PKG_VERSION% -X github.com/openshift/oc/pkg/version.gitTreeState=clean
        - go build -o %LIBRARY_BIN%\oc.exe -mod=vendor -tags "%TAGS%" -ldflags "%LDFLAGS%" ./cmd/oc
        - copy "%LIBRARY_BIN%\oc.exe" "%LIBRARY_BIN%\okd-cli.exe"

requirements:
  build:
    - ${{ compiler('go-nocgo') }} >=1.16
    - go-licenses >=2.0.1

tests:
  - package_contents:
      bin:
        - oc
        - okd-cli
      strict: true

about:
  homepage: https://www.okd.io/
  summary: OpenShift Command Line Interface
  description: |
    The OpenShift Command Line Interface (CLI), is a set of tools built on top of kubectl
    that help you work with OpenShift. With the CLI, you can create applications and manage
    OpenShift resources. It provides its full capabilities to connect with any Kubernetes
    compliant cluster, and adds commands simplifying interaction with an OpenShift cluster.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  repository: https://github.com/openshift/oc
  documentation: https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html

extra:
  recipe-maintainers:
    - chrisburr
    - delsner
    - phreed
