travis:
  secure:
    BINSTAR_TOKEN: BpsEC6wxt02CoWbe2DXt8hlbwiwCJU3OdPnOLcihI25z6gB+/d+JleiXsg9BZn6xi+vY4wO2Z1xLq928062CiLpV2cUeYmL2woiXG0/HwZse3RN0QMBWWqmnTpxpe1FjTME3ttZoye3WYxeydf6Pq+pD1f5boUCEkY+/3UnbhQ0t4xmPBulY1Uj0SuYZOajFHu+0RCwl4AQ/S23z5o9ScWi9A2htve25jtVlYqCfvErwiOEVrUEzRVEv3wdI17QYIpew4EGG3OHoFgFawF9Pm/9lTUhxKFQbDNg1oKmDEsk8GmRrjvFtcgQYAZ8AMTOZdb8FjQgvS/3QCvYj+48ynuSGod0V88Jrfg3SsspW8AOfufF3xQLtzhGhdn89cCc7J0Q7nzXaAW3eWS5xPDDXJ550GhPZK0J55+VWBGtSWZ/d+oeUs94IaF7ImhpXP9Okeigd1n1Q3tfTlEJkeMpP41e+f9A81GvOFu+5GFjjGG5L8hMXDbm1G6JWE6VYJLY3AXZfuz+UYT1KHUXFvj8tPlLWEN+RiXdbBIqvS4D+eTban9zvNaR1mIaNLuj1T0iXV8WVV9JqDYsJwgWmPRDRAYYFA2Zs3PhsYtBX8Q6wPhvgFWhrmGYETJACJ9ABcQwe/8C/dKXblP3t4PJTc5HvqcgzpkmzgNPW0qDjewOAccA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
